name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          zip -r jenv-${TAG_NAME}.zip * -x ".*"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.123dsa }}
          body_path: ./CHANGELOG.md
          files: |
            ./jenv-*.zip
